on:
  workflow_dispatch:

name: build-android

jobs:
  build-and-release:
    strategy:
      fail-fast: false
      matrix:
        include:
          # x86_64-android
          - arch-name: x86_64-android
            target: x86_64-linux-android
            file-ext:
          # aarch64-android
          - arch-name: aarch64-android
            target: aarch64-linux-android
            file-ext:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get the latest tag
        id: tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      - name: Build server
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: ndk
          args: --target ${{ matrix.target }} build --release -p tuic-server

      - name: Build client
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: ndk
          args: --target ${{ matrix.target }} build --release -p tuic-client

      - name: Move binaries
        run: |
          mkdir artifacts/
          mv target/${{ matrix.target }}/release/tuic-server${{ matrix.file-ext }} artifacts/tuic-server-${{ steps.tag.outputs.tag }}-${{ matrix.arch-name }}${{ matrix.file-ext }}
          mv target/${{ matrix.target }}/release/tuic-client${{ matrix.file-ext }} artifacts/tuic-client-${{ steps.tag.outputs.tag }}-${{ matrix.arch-name }}${{ matrix.file-ext }}

      - name: Calculate SHA256
        run: |
          cd artifacts/
          openssl dgst -sha256 -r tuic-server-${{ steps.tag.outputs.tag }}-${{ matrix.arch-name }}${{ matrix.file-ext }} > tuic-server-${{ steps.tag.outputs.tag }}-${{ matrix.arch-name }}${{ matrix.file-ext }}.sha256sum
          openssl dgst -sha256 -r tuic-client-${{ steps.tag.outputs.tag }}-${{ matrix.arch-name }}${{ matrix.file-ext }} > tuic-client-${{ steps.tag.outputs.tag }}-${{ matrix.arch-name }}${{ matrix.file-ext }}.sha256sum

      - uses: actions/upload-artifact@v2
        with:
          name: artifacts-${{ matrix.target }}
          path: "artifacts/*"
